version: "3.8"

services:
  postgres:
    container_name: postgres
    build:
      context: ./Postgres
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1' || exit 1"
      interval: 10s
      timeout: 1s
      retries: 1
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    container_name: nginx
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
