services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:17.4-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.4.2-alpine
    ports:
      - 6379:6379

  kafka:
    image: apache/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    networks:
      - default

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - '8080:8080'
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    depends_on:
      - kafka
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
