// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"Classroom/Tasks/pkg/events"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer {
	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer struct {
	mock.Mock
}

type MockProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducer) EXPECT() *MockProducer_Expecter {
	return &MockProducer_Expecter{mock: &_m.Mock}
}

// PublishTaskCreated provides a mock function for the type MockProducer
func (_mock *MockProducer) PublishTaskCreated(msg events.TaskCreated) error {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for PublishTaskCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(events.TaskCreated) error); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducer_PublishTaskCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishTaskCreated'
type MockProducer_PublishTaskCreated_Call struct {
	*mock.Call
}

// PublishTaskCreated is a helper method to define mock.On call
//   - msg
func (_e *MockProducer_Expecter) PublishTaskCreated(msg interface{}) *MockProducer_PublishTaskCreated_Call {
	return &MockProducer_PublishTaskCreated_Call{Call: _e.mock.On("PublishTaskCreated", msg)}
}

func (_c *MockProducer_PublishTaskCreated_Call) Run(run func(msg events.TaskCreated)) *MockProducer_PublishTaskCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(events.TaskCreated))
	})
	return _c
}

func (_c *MockProducer_PublishTaskCreated_Call) Return(err error) *MockProducer_PublishTaskCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducer_PublishTaskCreated_Call) RunAndReturn(run func(msg events.TaskCreated) error) *MockProducer_PublishTaskCreated_Call {
	_c.Call.Return(run)
	return _c
}
