port: 8080
postgres_url: 'postgres://postgres:password@localhost:5432/classroom?sslmode=disable'
redis_url: 'redis://localhost:6379/0'
auth:
  jwt_secret: secret
  access_ttl: 15m
  refresh_ttl: 720h
