variables:
  GO_VERSION: "1.24"

.build-template:
  stage: build
  image: ${IMAGE}
  script:
    - cd $SERVICE_PATH
    - go build -o ./bin/app ./cmd

build_lessons:
  extends: .build-template
  variables:
    SERVICE_PATH: ./Lessons
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      # changes:
      #   - ./Lessons
      when: always

build-tasks:
  extends: .build-template
  variables:
    SERVICE_PATH: ./Tasks
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      # changes:
      #   - ./Tasks
      when: always

build-courses:
  extends: .build-template
  variables:
    SERVICE_PATH: ./Courses
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      # changes:
      #   - ./Courses
      when: always

build-notifications:
  extends: .build-template
  variables:
    SERVICE_PATH: ./Notifications
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      # changes:
      #   - ./Notifications
      when: always

build-gateway:
  extends: .build-template
  variables:
    SERVICE_PATH: ./Gateway
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      # changes:
      #   - ./Gateway
      when: always

build-auth:
  extends: .build-template
  variables:
    SERVICE_PATH: ./Auth
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      # changes:
      #   - ./Auth
      when: always
