stages:
  - coverage

variables:
  GO_VERSION: '1.24'

.coverage-template:
  stage: coverage
  image: golang:${GO_VERSION}
  allow_failure: false
  variables:
    MIN_COVERAGE: 30
    CI_DEBUG_TRACE: 'false'
  before_script:
    - chmod +x ./Pipelines/cover/${CI_JOB_NAME}.sh
  script:
    - chmod +x ${CI_JOB_NAME}.sh
    - echo "🔍 Running tests with coverage..."
    - COVERAGE=$(./${CI_JOB_NAME}.sh)
    - EXIT_CODE=$?
    - if [ $EXIT_CODE -ne 0 ]; then
    - echo "❌ Unit tests failed!"
    - exit 1
    - fi
    - echo "📊 Test coverage:\ $COVERAGE% (minimum required:\ $MIN_COVERAGE%)"
    - if [ $COVERAGE -lt $MIN_COVERAGE ]; then
    - echo "❌ Coverage is below 30%"
    - exit 1
    - fi

# TODO: update target branch to main

auth-cover:
  extends: .coverage-template
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
      changes:
        - Auth/**/*
        - Common/Proto/auth.proto
      when: always

courses-cover:
  extends: .coverage-template
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
      changes:
        - Courses/**/*
      when: always

lessons-cover:
  extends: .coverage-template
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
      changes:
        - Lessons/**/*
      when: always

tasks-cover:
  extends: .coverage-template
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
      changes:
        - Tasks/**/*
      when: always

notifications-cover:
  extends: .coverage-template
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
      changes:
        - Notifications/**/*
      when: always
