// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: Common/Proto/courses.proto

package courses

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`          // ID курса
	TeacherId     string                 `protobuf:"bytes,2,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`       // ID Владельца
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                                // Название курса
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                    // Описание курса
	Visibility    bool                   `protobuf:"varint,5,opt,name=visibility,proto3" json:"visibility,omitempty"`                     // Видимость курса пользователю
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"` // Дата открытия доступа к курсу
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`       // Дата закрытия доступа к курсу
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_Common_Proto_courses_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{0}
}

func (x *Course) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Course) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *Course) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetVisibility() bool {
	if x != nil {
		return x.Visibility
	}
	return false
}

func (x *Course) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Course) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Visibility    bool                   `protobuf:"varint,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_Common_Proto_courses_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCourseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCourseRequest) GetVisibility() bool {
	if x != nil {
		return x.Visibility
	}
	return false
}

func (x *CreateCourseRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateCourseRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type CreateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseResponse) Reset() {
	*x = CreateCourseResponse{}
	mi := &file_Common_Proto_courses_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseResponse) ProtoMessage() {}

func (x *CreateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCourseResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseRequest) Reset() {
	*x = GetCourseRequest{}
	mi := &file_Common_Proto_courses_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseRequest) ProtoMessage() {}

func (x *GetCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseRequest.ProtoReflect.Descriptor instead.
func (*GetCourseRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{3}
}

func (x *GetCourseRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseResponse) Reset() {
	*x = GetCourseResponse{}
	mi := &file_Common_Proto_courses_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseResponse) ProtoMessage() {}

func (x *GetCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseResponse.ProtoReflect.Descriptor instead.
func (*GetCourseResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{4}
}

func (x *GetCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type GetCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // ID пользователя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesRequest) Reset() {
	*x = GetCoursesRequest{}
	mi := &file_Common_Proto_courses_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesRequest) ProtoMessage() {}

func (x *GetCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesRequest.ProtoReflect.Descriptor instead.
func (*GetCoursesRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{5}
}

func (x *GetCoursesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCoursesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        []*Course              `protobuf:"bytes,1,rep,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesResponse) Reset() {
	*x = GetCoursesResponse{}
	mi := &file_Common_Proto_courses_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesResponse) ProtoMessage() {}

func (x *GetCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesResponse.ProtoReflect.Descriptor instead.
func (*GetCoursesResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{6}
}

func (x *GetCoursesResponse) GetCourse() []*Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type UpdateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Visibility    *bool                  `protobuf:"varint,5,opt,name=visibility,proto3,oneof" json:"visibility,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseRequest) Reset() {
	*x = UpdateCourseRequest{}
	mi := &file_Common_Proto_courses_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseRequest) ProtoMessage() {}

func (x *UpdateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourseRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCourseRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UpdateCourseRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateCourseRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateCourseRequest) GetVisibility() bool {
	if x != nil && x.Visibility != nil {
		return *x.Visibility
	}
	return false
}

func (x *UpdateCourseRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UpdateCourseRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type UpdateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseResponse) Reset() {
	*x = UpdateCourseResponse{}
	mi := &file_Common_Proto_courses_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseResponse) ProtoMessage() {}

func (x *UpdateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseResponse.ProtoReflect.Descriptor instead.
func (*UpdateCourseResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{8}
}

type DeleteCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseRequest) Reset() {
	*x = DeleteCourseRequest{}
	mi := &file_Common_Proto_courses_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseRequest) ProtoMessage() {}

func (x *DeleteCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCourseRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type DeleteCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseResponse) Reset() {
	*x = DeleteCourseResponse{}
	mi := &file_Common_Proto_courses_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResponse) ProtoMessage() {}

func (x *DeleteCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{10}
}

type EnrollUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // ID ученика
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollUserRequest) Reset() {
	*x = EnrollUserRequest{}
	mi := &file_Common_Proto_courses_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollUserRequest) ProtoMessage() {}

func (x *EnrollUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollUserRequest.ProtoReflect.Descriptor instead.
func (*EnrollUserRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{11}
}

func (x *EnrollUserRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *EnrollUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type EnrollUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollUserResponse) Reset() {
	*x = EnrollUserResponse{}
	mi := &file_Common_Proto_courses_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollUserResponse) ProtoMessage() {}

func (x *EnrollUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollUserResponse.ProtoReflect.Descriptor instead.
func (*EnrollUserResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{12}
}

type ExpelUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpelUserRequest) Reset() {
	*x = ExpelUserRequest{}
	mi := &file_Common_Proto_courses_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpelUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpelUserRequest) ProtoMessage() {}

func (x *ExpelUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpelUserRequest.ProtoReflect.Descriptor instead.
func (*ExpelUserRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{13}
}

func (x *ExpelUserRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *ExpelUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ExpelUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpelUserResponse) Reset() {
	*x = ExpelUserResponse{}
	mi := &file_Common_Proto_courses_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpelUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpelUserResponse) ProtoMessage() {}

func (x *ExpelUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpelUserResponse.ProtoReflect.Descriptor instead.
func (*ExpelUserResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{14}
}

type IsTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsTeacherRequest) Reset() {
	*x = IsTeacherRequest{}
	mi := &file_Common_Proto_courses_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsTeacherRequest) ProtoMessage() {}

func (x *IsTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsTeacherRequest.ProtoReflect.Descriptor instead.
func (*IsTeacherRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{15}
}

func (x *IsTeacherRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IsTeacherRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type IsTeacherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsTeacher     bool                   `protobuf:"varint,1,opt,name=is_teacher,json=isTeacher,proto3" json:"is_teacher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsTeacherResponse) Reset() {
	*x = IsTeacherResponse{}
	mi := &file_Common_Proto_courses_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsTeacherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsTeacherResponse) ProtoMessage() {}

func (x *IsTeacherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsTeacherResponse.ProtoReflect.Descriptor instead.
func (*IsTeacherResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{16}
}

func (x *IsTeacherResponse) GetIsTeacher() bool {
	if x != nil {
		return x.IsTeacher
	}
	return false
}

type IsMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberRequest) Reset() {
	*x = IsMemberRequest{}
	mi := &file_Common_Proto_courses_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberRequest) ProtoMessage() {}

func (x *IsMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberRequest.ProtoReflect.Descriptor instead.
func (*IsMemberRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{17}
}

func (x *IsMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IsMemberRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type IsMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberResponse) Reset() {
	*x = IsMemberResponse{}
	mi := &file_Common_Proto_courses_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberResponse) ProtoMessage() {}

func (x *IsMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberResponse.ProtoReflect.Descriptor instead.
func (*IsMemberResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{18}
}

func (x *IsMemberResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

type GetCourseMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseMembersRequest) Reset() {
	*x = GetCourseMembersRequest{}
	mi := &file_Common_Proto_courses_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseMembersRequest) ProtoMessage() {}

func (x *GetCourseMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseMembersRequest.ProtoReflect.Descriptor instead.
func (*GetCourseMembersRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{19}
}

func (x *GetCourseMembersRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *GetCourseMembersRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GetCourseMembersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_Common_Proto_courses_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{20}
}

func (x *Member) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Member) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Member) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Member) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type GetCourseMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Members       []*Member              `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseMembersResponse) Reset() {
	*x = GetCourseMembersResponse{}
	mi := &file_Common_Proto_courses_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseMembersResponse) ProtoMessage() {}

func (x *GetCourseMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_courses_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseMembersResponse.ProtoReflect.Descriptor instead.
func (*GetCourseMembersResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_courses_proto_rawDescGZIP(), []int{21}
}

func (x *GetCourseMembersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetCourseMembersResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GetCourseMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_Common_Proto_courses_proto protoreflect.FileDescriptor

const file_Common_Proto_courses_proto_rawDesc = "" +
	"\n" +
	"\x1aCommon/Proto/courses.proto\x12\acourses\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x02\n" +
	"\x06Course\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x02 \x01(\tR\tteacherId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\bR\n" +
	"visibility\x12>\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartTime\x88\x01\x01\x12:\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendTime\x88\x01\x01B\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_time\"\x9e\x02\n" +
	"\x13CreateCourseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\bR\n" +
	"visibility\x12>\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartTime\x88\x01\x01\x12:\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendTime\x88\x01\x01B\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_time\"3\n" +
	"\x14CreateCourseResponse\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"/\n" +
	"\x10GetCourseRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"<\n" +
	"\x11GetCourseResponse\x12'\n" +
	"\x06course\x18\x01 \x01(\v2\x0f.courses.CourseR\x06course\",\n" +
	"\x11GetCoursesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"=\n" +
	"\x12GetCoursesResponse\x12'\n" +
	"\x06course\x18\x01 \x03(\v2\x0f.courses.CourseR\x06course\"\xda\x02\n" +
	"\x13UpdateCourseRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12#\n" +
	"\n" +
	"visibility\x18\x05 \x01(\bH\x02R\n" +
	"visibility\x88\x01\x01\x12>\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\tstartTime\x88\x01\x01\x12:\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x04R\aendTime\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_visibilityB\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_time\"\x16\n" +
	"\x14UpdateCourseResponse\"2\n" +
	"\x13DeleteCourseRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"\x16\n" +
	"\x14DeleteCourseResponse\"I\n" +
	"\x11EnrollUserRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x14\n" +
	"\x12EnrollUserResponse\"H\n" +
	"\x10ExpelUserRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x13\n" +
	"\x11ExpelUserResponse\"H\n" +
	"\x10IsTeacherRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"2\n" +
	"\x11IsTeacherResponse\x12\x1d\n" +
	"\n" +
	"is_teacher\x18\x01 \x01(\bR\tisTeacher\"G\n" +
	"\x0fIsMemberRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"/\n" +
	"\x10IsMemberResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\"b\n" +
	"\x17GetCourseMembersRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"s\n" +
	"\x06Member\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\"q\n" +
	"\x18GetCourseMembersResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12)\n" +
	"\amembers\x18\x03 \x03(\v2\x0f.courses.MemberR\amembers2\xeb\x05\n" +
	"\x0eCoursesService\x12K\n" +
	"\fCreateCourse\x12\x1c.courses.CreateCourseRequest\x1a\x1d.courses.CreateCourseResponse\x12B\n" +
	"\tGetCourse\x12\x19.courses.GetCourseRequest\x1a\x1a.courses.GetCourseResponse\x12E\n" +
	"\n" +
	"GetCourses\x12\x1a.courses.GetCoursesRequest\x1a\x1b.courses.GetCoursesResponse\x12K\n" +
	"\fUpdateCourse\x12\x1c.courses.UpdateCourseRequest\x1a\x1d.courses.UpdateCourseResponse\x12K\n" +
	"\fDeleteCourse\x12\x1c.courses.DeleteCourseRequest\x1a\x1d.courses.DeleteCourseResponse\x12E\n" +
	"\n" +
	"EnrollUser\x12\x1a.courses.EnrollUserRequest\x1a\x1b.courses.EnrollUserResponse\x12B\n" +
	"\tExpelUser\x12\x19.courses.ExpelUserRequest\x1a\x1a.courses.ExpelUserResponse\x12B\n" +
	"\tIsTeacher\x12\x19.courses.IsTeacherRequest\x1a\x1a.courses.IsTeacherResponse\x12?\n" +
	"\bIsMember\x12\x18.courses.IsMemberRequest\x1a\x19.courses.IsMemberResponse\x12W\n" +
	"\x10GetCourseMembers\x12 .courses.GetCourseMembersRequest\x1a!.courses.GetCourseMembersResponseB\rZ\vapi/coursesb\x06proto3"

var (
	file_Common_Proto_courses_proto_rawDescOnce sync.Once
	file_Common_Proto_courses_proto_rawDescData []byte
)

func file_Common_Proto_courses_proto_rawDescGZIP() []byte {
	file_Common_Proto_courses_proto_rawDescOnce.Do(func() {
		file_Common_Proto_courses_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Common_Proto_courses_proto_rawDesc), len(file_Common_Proto_courses_proto_rawDesc)))
	})
	return file_Common_Proto_courses_proto_rawDescData
}

var file_Common_Proto_courses_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_Common_Proto_courses_proto_goTypes = []any{
	(*Course)(nil),                   // 0: courses.Course
	(*CreateCourseRequest)(nil),      // 1: courses.CreateCourseRequest
	(*CreateCourseResponse)(nil),     // 2: courses.CreateCourseResponse
	(*GetCourseRequest)(nil),         // 3: courses.GetCourseRequest
	(*GetCourseResponse)(nil),        // 4: courses.GetCourseResponse
	(*GetCoursesRequest)(nil),        // 5: courses.GetCoursesRequest
	(*GetCoursesResponse)(nil),       // 6: courses.GetCoursesResponse
	(*UpdateCourseRequest)(nil),      // 7: courses.UpdateCourseRequest
	(*UpdateCourseResponse)(nil),     // 8: courses.UpdateCourseResponse
	(*DeleteCourseRequest)(nil),      // 9: courses.DeleteCourseRequest
	(*DeleteCourseResponse)(nil),     // 10: courses.DeleteCourseResponse
	(*EnrollUserRequest)(nil),        // 11: courses.EnrollUserRequest
	(*EnrollUserResponse)(nil),       // 12: courses.EnrollUserResponse
	(*ExpelUserRequest)(nil),         // 13: courses.ExpelUserRequest
	(*ExpelUserResponse)(nil),        // 14: courses.ExpelUserResponse
	(*IsTeacherRequest)(nil),         // 15: courses.IsTeacherRequest
	(*IsTeacherResponse)(nil),        // 16: courses.IsTeacherResponse
	(*IsMemberRequest)(nil),          // 17: courses.IsMemberRequest
	(*IsMemberResponse)(nil),         // 18: courses.IsMemberResponse
	(*GetCourseMembersRequest)(nil),  // 19: courses.GetCourseMembersRequest
	(*Member)(nil),                   // 20: courses.Member
	(*GetCourseMembersResponse)(nil), // 21: courses.GetCourseMembersResponse
	(*timestamppb.Timestamp)(nil),    // 22: google.protobuf.Timestamp
}
var file_Common_Proto_courses_proto_depIdxs = []int32{
	22, // 0: courses.Course.start_time:type_name -> google.protobuf.Timestamp
	22, // 1: courses.Course.end_time:type_name -> google.protobuf.Timestamp
	22, // 2: courses.CreateCourseRequest.start_time:type_name -> google.protobuf.Timestamp
	22, // 3: courses.CreateCourseRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 4: courses.GetCourseResponse.course:type_name -> courses.Course
	0,  // 5: courses.GetCoursesResponse.course:type_name -> courses.Course
	22, // 6: courses.UpdateCourseRequest.start_time:type_name -> google.protobuf.Timestamp
	22, // 7: courses.UpdateCourseRequest.end_time:type_name -> google.protobuf.Timestamp
	20, // 8: courses.GetCourseMembersResponse.members:type_name -> courses.Member
	1,  // 9: courses.CoursesService.CreateCourse:input_type -> courses.CreateCourseRequest
	3,  // 10: courses.CoursesService.GetCourse:input_type -> courses.GetCourseRequest
	5,  // 11: courses.CoursesService.GetCourses:input_type -> courses.GetCoursesRequest
	7,  // 12: courses.CoursesService.UpdateCourse:input_type -> courses.UpdateCourseRequest
	9,  // 13: courses.CoursesService.DeleteCourse:input_type -> courses.DeleteCourseRequest
	11, // 14: courses.CoursesService.EnrollUser:input_type -> courses.EnrollUserRequest
	13, // 15: courses.CoursesService.ExpelUser:input_type -> courses.ExpelUserRequest
	15, // 16: courses.CoursesService.IsTeacher:input_type -> courses.IsTeacherRequest
	17, // 17: courses.CoursesService.IsMember:input_type -> courses.IsMemberRequest
	19, // 18: courses.CoursesService.GetCourseMembers:input_type -> courses.GetCourseMembersRequest
	2,  // 19: courses.CoursesService.CreateCourse:output_type -> courses.CreateCourseResponse
	4,  // 20: courses.CoursesService.GetCourse:output_type -> courses.GetCourseResponse
	6,  // 21: courses.CoursesService.GetCourses:output_type -> courses.GetCoursesResponse
	8,  // 22: courses.CoursesService.UpdateCourse:output_type -> courses.UpdateCourseResponse
	10, // 23: courses.CoursesService.DeleteCourse:output_type -> courses.DeleteCourseResponse
	12, // 24: courses.CoursesService.EnrollUser:output_type -> courses.EnrollUserResponse
	14, // 25: courses.CoursesService.ExpelUser:output_type -> courses.ExpelUserResponse
	16, // 26: courses.CoursesService.IsTeacher:output_type -> courses.IsTeacherResponse
	18, // 27: courses.CoursesService.IsMember:output_type -> courses.IsMemberResponse
	21, // 28: courses.CoursesService.GetCourseMembers:output_type -> courses.GetCourseMembersResponse
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_Common_Proto_courses_proto_init() }
func file_Common_Proto_courses_proto_init() {
	if File_Common_Proto_courses_proto != nil {
		return
	}
	file_Common_Proto_courses_proto_msgTypes[0].OneofWrappers = []any{}
	file_Common_Proto_courses_proto_msgTypes[1].OneofWrappers = []any{}
	file_Common_Proto_courses_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Common_Proto_courses_proto_rawDesc), len(file_Common_Proto_courses_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Common_Proto_courses_proto_goTypes,
		DependencyIndexes: file_Common_Proto_courses_proto_depIdxs,
		MessageInfos:      file_Common_Proto_courses_proto_msgTypes,
	}.Build()
	File_Common_Proto_courses_proto = out.File
	file_Common_Proto_courses_proto_goTypes = nil
	file_Common_Proto_courses_proto_depIdxs = nil
}
