// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: Common/Proto/lesson.proto

package lesson

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lesson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`    // ID урока
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`    // ID курса
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                          // Название урока
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`              // Описание урока
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Время создания урока
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lesson) Reset() {
	*x = Lesson{}
	mi := &file_Common_Proto_lesson_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lesson) ProtoMessage() {}

func (x *Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_lesson_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lesson.ProtoReflect.Descriptor instead.
func (*Lesson) Descriptor() ([]byte, []int) {
	return file_Common_Proto_lesson_proto_rawDescGZIP(), []int{0}
}

func (x *Lesson) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *Lesson) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Lesson) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lesson) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Lesson) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLessonRequest) Reset() {
	*x = CreateLessonRequest{}
	mi := &file_Common_Proto_lesson_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonRequest) ProtoMessage() {}

func (x *CreateLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_lesson_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonRequest.ProtoReflect.Descriptor instead.
func (*CreateLessonRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_lesson_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLessonRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateLessonRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLessonRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLessonResponse) Reset() {
	*x = CreateLessonResponse{}
	mi := &file_Common_Proto_lesson_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonResponse) ProtoMessage() {}

func (x *CreateLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_lesson_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonResponse.ProtoReflect.Descriptor instead.
func (*CreateLessonResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_lesson_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLessonResponse) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

type GetLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonRequest) Reset() {
	*x = GetLessonRequest{}
	mi := &file_Common_Proto_lesson_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonRequest) ProtoMessage() {}

func (x *GetLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_lesson_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonRequest.ProtoReflect.Descriptor instead.
func (*GetLessonRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_lesson_proto_rawDescGZIP(), []int{3}
}

func (x *GetLessonRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

type GetLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonResponse) Reset() {
	*x = GetLessonResponse{}
	mi := &file_Common_Proto_lesson_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonResponse) ProtoMessage() {}

func (x *GetLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_lesson_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonResponse.ProtoReflect.Descriptor instead.
func (*GetLessonResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_lesson_proto_rawDescGZIP(), []int{4}
}

func (x *GetLessonResponse) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type GetLessonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonsRequest) Reset() {
	*x = GetLessonsRequest{}
	mi := &file_Common_Proto_lesson_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonsRequest) ProtoMessage() {}

func (x *GetLessonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_lesson_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonsRequest.ProtoReflect.Descriptor instead.
func (*GetLessonsRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_lesson_proto_rawDescGZIP(), []int{5}
}

func (x *GetLessonsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetLessonsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lessons       []*Lesson              `protobuf:"bytes,1,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonsResponse) Reset() {
	*x = GetLessonsResponse{}
	mi := &file_Common_Proto_lesson_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonsResponse) ProtoMessage() {}

func (x *GetLessonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_lesson_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonsResponse.ProtoReflect.Descriptor instead.
func (*GetLessonsResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_lesson_proto_rawDescGZIP(), []int{6}
}

func (x *GetLessonsResponse) GetLessons() []*Lesson {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type UpdateLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLessonRequest) Reset() {
	*x = UpdateLessonRequest{}
	mi := &file_Common_Proto_lesson_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLessonRequest) ProtoMessage() {}

func (x *UpdateLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_lesson_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLessonRequest.ProtoReflect.Descriptor instead.
func (*UpdateLessonRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_lesson_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLessonRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *UpdateLessonRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateLessonRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type UpdateLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLessonResponse) Reset() {
	*x = UpdateLessonResponse{}
	mi := &file_Common_Proto_lesson_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLessonResponse) ProtoMessage() {}

func (x *UpdateLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_lesson_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLessonResponse.ProtoReflect.Descriptor instead.
func (*UpdateLessonResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_lesson_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateLessonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLessonRequest) Reset() {
	*x = DeleteLessonRequest{}
	mi := &file_Common_Proto_lesson_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLessonRequest) ProtoMessage() {}

func (x *DeleteLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_lesson_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLessonRequest.ProtoReflect.Descriptor instead.
func (*DeleteLessonRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_lesson_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteLessonRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

type DeleteLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLessonResponse) Reset() {
	*x = DeleteLessonResponse{}
	mi := &file_Common_Proto_lesson_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLessonResponse) ProtoMessage() {}

func (x *DeleteLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_lesson_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLessonResponse.ProtoReflect.Descriptor instead.
func (*DeleteLessonResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_lesson_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteLessonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_Common_Proto_lesson_proto protoreflect.FileDescriptor

const file_Common_Proto_lesson_proto_rawDesc = "" +
	"\n" +
	"\x19Common/Proto/lesson.proto\x12\x06lesson\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x01\n" +
	"\x06Lesson\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"j\n" +
	"\x13CreateLessonRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"3\n" +
	"\x14CreateLessonResponse\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\"/\n" +
	"\x10GetLessonRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\";\n" +
	"\x11GetLessonResponse\x12&\n" +
	"\x06lesson\x18\x01 \x01(\v2\x0e.lesson.LessonR\x06lesson\"0\n" +
	"\x11GetLessonsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\">\n" +
	"\x12GetLessonsResponse\x12(\n" +
	"\alessons\x18\x01 \x03(\v2\x0e.lesson.LessonR\alessons\"\x8e\x01\n" +
	"\x13UpdateLessonRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_description\"0\n" +
	"\x14UpdateLessonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x13DeleteLessonRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\"0\n" +
	"\x14DeleteLessonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf7\x02\n" +
	"\rLessonService\x12I\n" +
	"\fCreateLesson\x12\x1b.lesson.CreateLessonRequest\x1a\x1c.lesson.CreateLessonResponse\x12@\n" +
	"\tGetLesson\x12\x18.lesson.GetLessonRequest\x1a\x19.lesson.GetLessonResponse\x12C\n" +
	"\n" +
	"GetLessons\x12\x19.lesson.GetLessonsRequest\x1a\x1a.lesson.GetLessonsResponse\x12I\n" +
	"\fUpdateLesson\x12\x1b.lesson.UpdateLessonRequest\x1a\x1c.lesson.UpdateLessonResponse\x12I\n" +
	"\fDeleteLesson\x12\x1b.lesson.DeleteLessonRequest\x1a\x1c.lesson.DeleteLessonResponseB\fZ\n" +
	"api/lessonb\x06proto3"

var (
	file_Common_Proto_lesson_proto_rawDescOnce sync.Once
	file_Common_Proto_lesson_proto_rawDescData []byte
)

func file_Common_Proto_lesson_proto_rawDescGZIP() []byte {
	file_Common_Proto_lesson_proto_rawDescOnce.Do(func() {
		file_Common_Proto_lesson_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Common_Proto_lesson_proto_rawDesc), len(file_Common_Proto_lesson_proto_rawDesc)))
	})
	return file_Common_Proto_lesson_proto_rawDescData
}

var file_Common_Proto_lesson_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_Common_Proto_lesson_proto_goTypes = []any{
	(*Lesson)(nil),                // 0: lesson.Lesson
	(*CreateLessonRequest)(nil),   // 1: lesson.CreateLessonRequest
	(*CreateLessonResponse)(nil),  // 2: lesson.CreateLessonResponse
	(*GetLessonRequest)(nil),      // 3: lesson.GetLessonRequest
	(*GetLessonResponse)(nil),     // 4: lesson.GetLessonResponse
	(*GetLessonsRequest)(nil),     // 5: lesson.GetLessonsRequest
	(*GetLessonsResponse)(nil),    // 6: lesson.GetLessonsResponse
	(*UpdateLessonRequest)(nil),   // 7: lesson.UpdateLessonRequest
	(*UpdateLessonResponse)(nil),  // 8: lesson.UpdateLessonResponse
	(*DeleteLessonRequest)(nil),   // 9: lesson.DeleteLessonRequest
	(*DeleteLessonResponse)(nil),  // 10: lesson.DeleteLessonResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_Common_Proto_lesson_proto_depIdxs = []int32{
	11, // 0: lesson.Lesson.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: lesson.GetLessonResponse.lesson:type_name -> lesson.Lesson
	0,  // 2: lesson.GetLessonsResponse.lessons:type_name -> lesson.Lesson
	1,  // 3: lesson.LessonService.CreateLesson:input_type -> lesson.CreateLessonRequest
	3,  // 4: lesson.LessonService.GetLesson:input_type -> lesson.GetLessonRequest
	5,  // 5: lesson.LessonService.GetLessons:input_type -> lesson.GetLessonsRequest
	7,  // 6: lesson.LessonService.UpdateLesson:input_type -> lesson.UpdateLessonRequest
	9,  // 7: lesson.LessonService.DeleteLesson:input_type -> lesson.DeleteLessonRequest
	2,  // 8: lesson.LessonService.CreateLesson:output_type -> lesson.CreateLessonResponse
	4,  // 9: lesson.LessonService.GetLesson:output_type -> lesson.GetLessonResponse
	6,  // 10: lesson.LessonService.GetLessons:output_type -> lesson.GetLessonsResponse
	8,  // 11: lesson.LessonService.UpdateLesson:output_type -> lesson.UpdateLessonResponse
	10, // 12: lesson.LessonService.DeleteLesson:output_type -> lesson.DeleteLessonResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_Common_Proto_lesson_proto_init() }
func file_Common_Proto_lesson_proto_init() {
	if File_Common_Proto_lesson_proto != nil {
		return
	}
	file_Common_Proto_lesson_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Common_Proto_lesson_proto_rawDesc), len(file_Common_Proto_lesson_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Common_Proto_lesson_proto_goTypes,
		DependencyIndexes: file_Common_Proto_lesson_proto_depIdxs,
		MessageInfos:      file_Common_Proto_lesson_proto_msgTypes,
	}.Build()
	File_Common_Proto_lesson_proto = out.File
	file_Common_Proto_lesson_proto_goTypes = nil
	file_Common_Proto_lesson_proto_depIdxs = nil
}
