// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entities "Classroom/Auth/internal/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TokenRepo is an autogenerated mock type for the TokenRepo type
type TokenRepo struct {
	mock.Mock
}

type TokenRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenRepo) EXPECT() *TokenRepo_Expecter {
	return &TokenRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, ttl
func (_m *TokenRepo) Create(ctx context.Context, userID string, ttl time.Duration) (string, error) {
	ret := _m.Called(ctx, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return rf(ctx, userID, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = rf(ctx, userID, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, userID, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TokenRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - ttl time.Duration
func (_e *TokenRepo_Expecter) Create(ctx interface{}, userID interface{}, ttl interface{}) *TokenRepo_Create_Call {
	return &TokenRepo_Create_Call{Call: _e.mock.On("Create", ctx, userID, ttl)}
}

func (_c *TokenRepo_Create_Call) Run(run func(ctx context.Context, userID string, ttl time.Duration)) *TokenRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *TokenRepo_Create_Call) Return(_a0 string, _a1 error) *TokenRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenRepo_Create_Call) RunAndReturn(run func(context.Context, string, time.Duration) (string, error)) *TokenRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetInfoByToken provides a mock function with given fields: ctx, token
func (_m *TokenRepo) GetInfoByToken(ctx context.Context, token string) (entities.RefreshToken, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetInfoByToken")
	}

	var r0 entities.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.RefreshToken, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.RefreshToken); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(entities.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenRepo_GetInfoByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInfoByToken'
type TokenRepo_GetInfoByToken_Call struct {
	*mock.Call
}

// GetInfoByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *TokenRepo_Expecter) GetInfoByToken(ctx interface{}, token interface{}) *TokenRepo_GetInfoByToken_Call {
	return &TokenRepo_GetInfoByToken_Call{Call: _e.mock.On("GetInfoByToken", ctx, token)}
}

func (_c *TokenRepo_GetInfoByToken_Call) Run(run func(ctx context.Context, token string)) *TokenRepo_GetInfoByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TokenRepo_GetInfoByToken_Call) Return(_a0 entities.RefreshToken, _a1 error) *TokenRepo_GetInfoByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenRepo_GetInfoByToken_Call) RunAndReturn(run func(context.Context, string) (entities.RefreshToken, error)) *TokenRepo_GetInfoByToken_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, token
func (_m *TokenRepo) Revoke(ctx context.Context, token string) (bool, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenRepo_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type TokenRepo_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *TokenRepo_Expecter) Revoke(ctx interface{}, token interface{}) *TokenRepo_Revoke_Call {
	return &TokenRepo_Revoke_Call{Call: _e.mock.On("Revoke", ctx, token)}
}

func (_c *TokenRepo_Revoke_Call) Run(run func(ctx context.Context, token string)) *TokenRepo_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TokenRepo_Revoke_Call) Return(_a0 bool, _a1 error) *TokenRepo_Revoke_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenRepo_Revoke_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *TokenRepo_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenRepo creates a new instance of TokenRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenRepo {
	mock := &TokenRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
