API-Gateway:
    Host:
        Address: 0.0.0.0
        Port: 8080
    Auth:
        Address: auth-service
        Port: 50051
        Enabled: true
    Courses:
        Address: 127.0.0.1
        Port: 50151
        Enabled: false
    Lessons:
        Address: 127.0.0.1
        Port: 50251
        Enabled: false
    Tasks:
        Address: 127.0.0.1
        Port: 50351
        Enabled: false
    Notifications:
        Address: 127.0.0.1
        Port: 50451
        Enabled: false
    Chat:
        Address: 127.0.0.1
        Port: 50551
        Enabled: false