// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controller

import (
	"Classroom/Lessons/internal/domain"
	"Classroom/Lessons/internal/dto"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLessonService creates a new instance of MockLessonService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLessonService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLessonService {
	mock := &MockLessonService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLessonService is an autogenerated mock type for the LessonService type
type MockLessonService struct {
	mock.Mock
}

type MockLessonService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLessonService) EXPECT() *MockLessonService_Expecter {
	return &MockLessonService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockLessonService
func (_mock *MockLessonService) Create(ctx context.Context, dto1 dto.CreateLessonDTO) (domain.Lesson, error) {
	ret := _mock.Called(ctx, dto1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Lesson
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateLessonDTO) (domain.Lesson, error)); ok {
		return returnFunc(ctx, dto1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateLessonDTO) domain.Lesson); ok {
		r0 = returnFunc(ctx, dto1)
	} else {
		r0 = ret.Get(0).(domain.Lesson)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CreateLessonDTO) error); ok {
		r1 = returnFunc(ctx, dto1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLessonService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLessonService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - dto1
func (_e *MockLessonService_Expecter) Create(ctx interface{}, dto1 interface{}) *MockLessonService_Create_Call {
	return &MockLessonService_Create_Call{Call: _e.mock.On("Create", ctx, dto1)}
}

func (_c *MockLessonService_Create_Call) Run(run func(ctx context.Context, dto1 dto.CreateLessonDTO)) *MockLessonService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateLessonDTO))
	})
	return _c
}

func (_c *MockLessonService_Create_Call) Return(lesson domain.Lesson, err error) *MockLessonService_Create_Call {
	_c.Call.Return(lesson, err)
	return _c
}

func (_c *MockLessonService_Create_Call) RunAndReturn(run func(ctx context.Context, dto1 dto.CreateLessonDTO) (domain.Lesson, error)) *MockLessonService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockLessonService
func (_mock *MockLessonService) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLessonService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLessonService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockLessonService_Expecter) Delete(ctx interface{}, id interface{}) *MockLessonService_Delete_Call {
	return &MockLessonService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockLessonService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockLessonService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLessonService_Delete_Call) Return(err error) *MockLessonService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLessonService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockLessonService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockLessonService
func (_mock *MockLessonService) GetByID(ctx context.Context, id string) (domain.Lesson, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Lesson
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Lesson, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Lesson); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Lesson)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLessonService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockLessonService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockLessonService_Expecter) GetByID(ctx interface{}, id interface{}) *MockLessonService_GetByID_Call {
	return &MockLessonService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockLessonService_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockLessonService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLessonService_GetByID_Call) Return(lesson domain.Lesson, err error) *MockLessonService_GetByID_Call {
	_c.Call.Return(lesson, err)
	return _c
}

func (_c *MockLessonService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (domain.Lesson, error)) *MockLessonService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCourseID provides a mock function for the type MockLessonService
func (_mock *MockLessonService) ListByCourseID(ctx context.Context, courseID string) ([]domain.Lesson, error) {
	ret := _mock.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCourseID")
	}

	var r0 []domain.Lesson
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Lesson, error)); ok {
		return returnFunc(ctx, courseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Lesson); ok {
		r0 = returnFunc(ctx, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Lesson)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLessonService_ListByCourseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCourseID'
type MockLessonService_ListByCourseID_Call struct {
	*mock.Call
}

// ListByCourseID is a helper method to define mock.On call
//   - ctx
//   - courseID
func (_e *MockLessonService_Expecter) ListByCourseID(ctx interface{}, courseID interface{}) *MockLessonService_ListByCourseID_Call {
	return &MockLessonService_ListByCourseID_Call{Call: _e.mock.On("ListByCourseID", ctx, courseID)}
}

func (_c *MockLessonService_ListByCourseID_Call) Run(run func(ctx context.Context, courseID string)) *MockLessonService_ListByCourseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLessonService_ListByCourseID_Call) Return(lessons []domain.Lesson, err error) *MockLessonService_ListByCourseID_Call {
	_c.Call.Return(lessons, err)
	return _c
}

func (_c *MockLessonService_ListByCourseID_Call) RunAndReturn(run func(ctx context.Context, courseID string) ([]domain.Lesson, error)) *MockLessonService_ListByCourseID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockLessonService
func (_mock *MockLessonService) Update(ctx context.Context, dto1 dto.UpdateLessonDTO) (domain.Lesson, error) {
	ret := _mock.Called(ctx, dto1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Lesson
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UpdateLessonDTO) (domain.Lesson, error)); ok {
		return returnFunc(ctx, dto1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UpdateLessonDTO) domain.Lesson); ok {
		r0 = returnFunc(ctx, dto1)
	} else {
		r0 = ret.Get(0).(domain.Lesson)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.UpdateLessonDTO) error); ok {
		r1 = returnFunc(ctx, dto1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLessonService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockLessonService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx
//   - dto1
func (_e *MockLessonService_Expecter) Update(ctx interface{}, dto1 interface{}) *MockLessonService_Update_Call {
	return &MockLessonService_Update_Call{Call: _e.mock.On("Update", ctx, dto1)}
}

func (_c *MockLessonService_Update_Call) Run(run func(ctx context.Context, dto1 dto.UpdateLessonDTO)) *MockLessonService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.UpdateLessonDTO))
	})
	return _c
}

func (_c *MockLessonService_Update_Call) Return(lesson domain.Lesson, err error) *MockLessonService_Update_Call {
	_c.Call.Return(lesson, err)
	return _c
}

func (_c *MockLessonService_Update_Call) RunAndReturn(run func(ctx context.Context, dto1 dto.UpdateLessonDTO) (domain.Lesson, error)) *MockLessonService_Update_Call {
	_c.Call.Return(run)
	return _c
}
