// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: Common/Proto/tasks.proto

package tasks

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`          // ID задания
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`    // ID курса
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                          // Название задания
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                      // Содержание задания
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Дата создания задания
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type StudentTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`          // ID задания
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`    // ID курса
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                          // Название задания
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                      // Содержание задания
	Completed     bool                   `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"`                 // Выполнено ли задание
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Дата создания задания
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentTask) Reset() {
	*x = StudentTask{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentTask) ProtoMessage() {}

func (x *StudentTask) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentTask.ProtoReflect.Descriptor instead.
func (*StudentTask) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *StudentTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StudentTask) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *StudentTask) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StudentTask) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StudentTask) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *StudentTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TaskStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`          // ID задания
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"` // ID пользователя
	Completed     bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`                 // Выполнено ли задание
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *TaskStatus) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatus) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *TaskStatus) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTaskRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{6}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{7}
}

func (x *GetTasksRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksResponse) Reset() {
	*x = GetTasksResponse{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResponse) ProtoMessage() {}

func (x *GetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResponse.ProtoReflect.Descriptor instead.
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{8}
}

func (x *GetTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *string                `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Content       *string                `protobuf:"bytes,2,opt,name=content,proto3,oneof" json:"content,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTaskRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateTaskRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *UpdateTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ChangeStatusTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeStatusTaskRequest) Reset() {
	*x = ChangeStatusTaskRequest{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeStatusTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStatusTaskRequest) ProtoMessage() {}

func (x *ChangeStatusTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStatusTaskRequest.ProtoReflect.Descriptor instead.
func (*ChangeStatusTaskRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeStatusTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ChangeStatusTaskRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type ChangeStatusTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskStatus    bool                   `protobuf:"varint,1,opt,name=task_status,json=taskStatus,proto3" json:"task_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeStatusTaskResponse) Reset() {
	*x = ChangeStatusTaskResponse{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeStatusTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStatusTaskResponse) ProtoMessage() {}

func (x *ChangeStatusTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStatusTaskResponse.ProtoReflect.Descriptor instead.
func (*ChangeStatusTaskResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeStatusTaskResponse) GetTaskStatus() bool {
	if x != nil {
		return x.TaskStatus
	}
	return false
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetTasksForStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksForStudentRequest) Reset() {
	*x = GetTasksForStudentRequest{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksForStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksForStudentRequest) ProtoMessage() {}

func (x *GetTasksForStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksForStudentRequest.ProtoReflect.Descriptor instead.
func (*GetTasksForStudentRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{15}
}

func (x *GetTasksForStudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetTasksForStudentRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetTasksForStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*StudentTask         `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksForStudentResponse) Reset() {
	*x = GetTasksForStudentResponse{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksForStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksForStudentResponse) ProtoMessage() {}

func (x *GetTasksForStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksForStudentResponse.ProtoReflect.Descriptor instead.
func (*GetTasksForStudentResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{16}
}

func (x *GetTasksForStudentResponse) GetTasks() []*StudentTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetStudentStatusesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentStatusesRequest) Reset() {
	*x = GetStudentStatusesRequest{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentStatusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentStatusesRequest) ProtoMessage() {}

func (x *GetStudentStatusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentStatusesRequest.ProtoReflect.Descriptor instead.
func (*GetStudentStatusesRequest) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{17}
}

func (x *GetStudentStatusesRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetStudentStatusesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*TaskStatus          `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentStatusesResponse) Reset() {
	*x = GetStudentStatusesResponse{}
	mi := &file_Common_Proto_tasks_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentStatusesResponse) ProtoMessage() {}

func (x *GetStudentStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Common_Proto_tasks_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentStatusesResponse.ProtoReflect.Descriptor instead.
func (*GetStudentStatusesResponse) Descriptor() ([]byte, []int) {
	return file_Common_Proto_tasks_proto_rawDescGZIP(), []int{18}
}

func (x *GetStudentStatusesResponse) GetStatuses() []*TaskStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

var File_Common_Proto_tasks_proto protoreflect.FileDescriptor

const file_Common_Proto_tasks_proto_rawDesc = "" +
	"\n" +
	"\x18Common/Proto/tasks.proto\x12\x05tasks\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xcc\x01\n" +
	"\vStudentTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\tcompleted\x18\x05 \x01(\bR\tcompleted\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"b\n" +
	"\n" +
	"TaskStatus\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\"h\n" +
	"\x11CreateTaskRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"-\n" +
	"\x12CreateTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"2\n" +
	"\x0fGetTaskResponse\x12\x1f\n" +
	"\x04task\x18\x01 \x01(\v2\v.tasks.TaskR\x04task\".\n" +
	"\x0fGetTasksRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"5\n" +
	"\x10GetTasksResponse\x12!\n" +
	"\x05tasks\x18\x01 \x03(\v2\v.tasks.TaskR\x05tasks\"|\n" +
	"\x11UpdateTaskRequest\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tH\x01R\acontent\x88\x01\x01\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskIdB\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_content\"5\n" +
	"\x12UpdateTaskResponse\x12\x1f\n" +
	"\x04task\x18\x01 \x01(\v2\v.tasks.TaskR\x04task\"Q\n" +
	"\x17ChangeStatusTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\";\n" +
	"\x18ChangeStatusTaskResponse\x12\x1f\n" +
	"\vtask_status\x18\x01 \x01(\bR\n" +
	"taskStatus\",\n" +
	"\x11DeleteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\".\n" +
	"\x12DeleteTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"W\n" +
	"\x19GetTasksForStudentRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"F\n" +
	"\x1aGetTasksForStudentResponse\x12(\n" +
	"\x05tasks\x18\x01 \x03(\v2\x12.tasks.StudentTaskR\x05tasks\"4\n" +
	"\x19GetStudentStatusesRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"K\n" +
	"\x1aGetStudentStatusesResponse\x12-\n" +
	"\bstatuses\x18\x01 \x03(\v2\x11.tasks.TaskStatusR\bstatuses2\xd9\x04\n" +
	"\fTasksService\x12A\n" +
	"\n" +
	"CreateTask\x12\x18.tasks.CreateTaskRequest\x1a\x19.tasks.CreateTaskResponse\x128\n" +
	"\aGetTask\x12\x15.tasks.GetTaskRequest\x1a\x16.tasks.GetTaskResponse\x12;\n" +
	"\bGetTasks\x12\x16.tasks.GetTasksRequest\x1a\x17.tasks.GetTasksResponse\x12Y\n" +
	"\x12GetTasksForStudent\x12 .tasks.GetTasksForStudentRequest\x1a!.tasks.GetTasksForStudentResponse\x12Y\n" +
	"\x12GetStudentStatuses\x12 .tasks.GetStudentStatusesRequest\x1a!.tasks.GetStudentStatusesResponse\x12A\n" +
	"\n" +
	"UpdateTask\x12\x18.tasks.UpdateTaskRequest\x1a\x19.tasks.UpdateTaskResponse\x12S\n" +
	"\x10ChangeStatusTask\x12\x1e.tasks.ChangeStatusTaskRequest\x1a\x1f.tasks.ChangeStatusTaskResponse\x12A\n" +
	"\n" +
	"DeleteTask\x12\x18.tasks.DeleteTaskRequest\x1a\x19.tasks.DeleteTaskResponseB\vZ\tapi/tasksb\x06proto3"

var (
	file_Common_Proto_tasks_proto_rawDescOnce sync.Once
	file_Common_Proto_tasks_proto_rawDescData []byte
)

func file_Common_Proto_tasks_proto_rawDescGZIP() []byte {
	file_Common_Proto_tasks_proto_rawDescOnce.Do(func() {
		file_Common_Proto_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Common_Proto_tasks_proto_rawDesc), len(file_Common_Proto_tasks_proto_rawDesc)))
	})
	return file_Common_Proto_tasks_proto_rawDescData
}

var file_Common_Proto_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_Common_Proto_tasks_proto_goTypes = []any{
	(*Task)(nil),                       // 0: tasks.Task
	(*StudentTask)(nil),                // 1: tasks.StudentTask
	(*TaskStatus)(nil),                 // 2: tasks.TaskStatus
	(*CreateTaskRequest)(nil),          // 3: tasks.CreateTaskRequest
	(*CreateTaskResponse)(nil),         // 4: tasks.CreateTaskResponse
	(*GetTaskRequest)(nil),             // 5: tasks.GetTaskRequest
	(*GetTaskResponse)(nil),            // 6: tasks.GetTaskResponse
	(*GetTasksRequest)(nil),            // 7: tasks.GetTasksRequest
	(*GetTasksResponse)(nil),           // 8: tasks.GetTasksResponse
	(*UpdateTaskRequest)(nil),          // 9: tasks.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),         // 10: tasks.UpdateTaskResponse
	(*ChangeStatusTaskRequest)(nil),    // 11: tasks.ChangeStatusTaskRequest
	(*ChangeStatusTaskResponse)(nil),   // 12: tasks.ChangeStatusTaskResponse
	(*DeleteTaskRequest)(nil),          // 13: tasks.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),         // 14: tasks.DeleteTaskResponse
	(*GetTasksForStudentRequest)(nil),  // 15: tasks.GetTasksForStudentRequest
	(*GetTasksForStudentResponse)(nil), // 16: tasks.GetTasksForStudentResponse
	(*GetStudentStatusesRequest)(nil),  // 17: tasks.GetStudentStatusesRequest
	(*GetStudentStatusesResponse)(nil), // 18: tasks.GetStudentStatusesResponse
	(*timestamppb.Timestamp)(nil),      // 19: google.protobuf.Timestamp
}
var file_Common_Proto_tasks_proto_depIdxs = []int32{
	19, // 0: tasks.Task.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: tasks.StudentTask.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: tasks.GetTaskResponse.task:type_name -> tasks.Task
	0,  // 3: tasks.GetTasksResponse.tasks:type_name -> tasks.Task
	0,  // 4: tasks.UpdateTaskResponse.task:type_name -> tasks.Task
	1,  // 5: tasks.GetTasksForStudentResponse.tasks:type_name -> tasks.StudentTask
	2,  // 6: tasks.GetStudentStatusesResponse.statuses:type_name -> tasks.TaskStatus
	3,  // 7: tasks.TasksService.CreateTask:input_type -> tasks.CreateTaskRequest
	5,  // 8: tasks.TasksService.GetTask:input_type -> tasks.GetTaskRequest
	7,  // 9: tasks.TasksService.GetTasks:input_type -> tasks.GetTasksRequest
	15, // 10: tasks.TasksService.GetTasksForStudent:input_type -> tasks.GetTasksForStudentRequest
	17, // 11: tasks.TasksService.GetStudentStatuses:input_type -> tasks.GetStudentStatusesRequest
	9,  // 12: tasks.TasksService.UpdateTask:input_type -> tasks.UpdateTaskRequest
	11, // 13: tasks.TasksService.ChangeStatusTask:input_type -> tasks.ChangeStatusTaskRequest
	13, // 14: tasks.TasksService.DeleteTask:input_type -> tasks.DeleteTaskRequest
	4,  // 15: tasks.TasksService.CreateTask:output_type -> tasks.CreateTaskResponse
	6,  // 16: tasks.TasksService.GetTask:output_type -> tasks.GetTaskResponse
	8,  // 17: tasks.TasksService.GetTasks:output_type -> tasks.GetTasksResponse
	16, // 18: tasks.TasksService.GetTasksForStudent:output_type -> tasks.GetTasksForStudentResponse
	18, // 19: tasks.TasksService.GetStudentStatuses:output_type -> tasks.GetStudentStatusesResponse
	10, // 20: tasks.TasksService.UpdateTask:output_type -> tasks.UpdateTaskResponse
	12, // 21: tasks.TasksService.ChangeStatusTask:output_type -> tasks.ChangeStatusTaskResponse
	14, // 22: tasks.TasksService.DeleteTask:output_type -> tasks.DeleteTaskResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_Common_Proto_tasks_proto_init() }
func file_Common_Proto_tasks_proto_init() {
	if File_Common_Proto_tasks_proto != nil {
		return
	}
	file_Common_Proto_tasks_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Common_Proto_tasks_proto_rawDesc), len(file_Common_Proto_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Common_Proto_tasks_proto_goTypes,
		DependencyIndexes: file_Common_Proto_tasks_proto_depIdxs,
		MessageInfos:      file_Common_Proto_tasks_proto_msgTypes,
	}.Build()
	File_Common_Proto_tasks_proto = out.File
	file_Common_Proto_tasks_proto_goTypes = nil
	file_Common_Proto_tasks_proto_depIdxs = nil
}
